name: Build Unleashed APK
on:
  workflow_dispatch:
    inputs:
      game_url:
        description: 'Прямая ссылка на ISO/ZIP'
        required: true
        type: string
      embed:
        description: 'Встроить игру?'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"
      - name: Download game
        run: wget ${{ github.event.inputs.game_url }} -O private/game.zip
      - name: Build APK
        run: |
          chmod +x build_android.sh
          ./build_android.sh
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Unleashed-APK
          path: android/app/build/outputs/apk/release/*.apk
